version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: abp_postgres
    environment:
      POSTGRES_DB: academic_management
      POSTGRES_USER: abp_user
      POSTGRES_PASSWORD: abp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abp_user -d academic_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
