version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: abp_backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      # Point this at your Railway connection string (set it in .env)
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      # Keep for hot-reload dev workflow; remove in production
      - ../src:/app/src:ro
      - ../prisma:/app/prisma:ro
    networks:
      - abp_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "
        echo 'Running Prisma migrations...' &&
        npx prisma migrate deploy &&
        echo 'Database migrations completed' &&
        npm start
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: abp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - abp_network
    profiles:
      - tools
    # Configure pgAdmin to connect to your Railway DB manually inside the UI.

networks:
  abp_network:
    driver: bridge